
# application.properites 설정일때

# 포트 설정
# server.port = 8081
##
# spring.mvc.view.prefix=WEB-INF/views/
# spring.mvc.view.suffix=.jsp

#application.yml
server:
  port: 8085

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
      
      

