
#application.yml
server:
  port: 8085

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: Service01
        

tiger:
 ribbon:
# 이제 아래는 의미가 없다 왜냐면 위에 유레카서버를 실행함으로써 name을 정해줬기에
#  service01, 02등으로 접근을 한다.
#  listOfServer: localhost:8086, localhost:8087

feign:
  hystrix:
    enabled: true
  